### ISSUE TITLE
Small Design Change Summary

### ISSUE THREAD

**Issue by ennerf** [HebiRobotics/scope2-feedback#83]
Below is a list of minor design changes that are currently listed in separate issues. This summary is intended to save some time looking for them.

**Welcome Page**
- [x] Add a link to Github issue tracker. Maybe below the link to docs.hebi.us (ref #81)

**Dashboard**
- [x] Make params section more dangerous looking (ref #76)

**Monitoring**
- [x] Add button to set Mobile accelerometer mode (ref #65)

**Gains**
- [x]  The "currently on the module" gains and safety parameters are in a grey color that is not very high-contrast to the background behind it. Could this text be darker (even black would be fine) to make it more visible? (ref #79, #71 )

**General**
- [x] selection colors are really hard to see (ref #69)
- [x] interface "refresh" icon looks like it is disabled (ref #70)
- [x] Highlighting Obscures Name in Main Panel (#27) (editing was removed, so maybe take out extra styling)

**Maybe**
- [x] Save or convert log files to formats other than .hebilog, particularly CSV (#42) (would be an extra popup window)
